// Code generated by "stringer -type=CardFamily"; DO NOT EDIT.

package own_deck

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Spades-0]
	_ = x[Diamons-1]
	_ = x[Clubs-2]
	_ = x[Hearts-3]
}

const _CardFamily_name = "SpadesDiamonsClubsHearts"

var _CardFamily_index = [...]uint8{0, 6, 13, 18, 24}

func (i CardFamily) String() string {
	if i < 0 || i >= CardFamily(len(_CardFamily_index)-1) {
		return "CardFamily(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CardFamily_name[_CardFamily_index[i]:_CardFamily_index[i+1]]
}
